// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package hyparview

func (r *JoinRequest) To() *Node {
	return r.to
}

func (r *JoinRequest) AssocTo(n *Node) Message {
	o := *r
	o.to = n
	return &o
}

func (r *ForwardJoinRequest) To() *Node {
	return r.to
}

func (r *ForwardJoinRequest) AssocTo(n *Node) Message {
	o := *r
	o.to = n
	return &o
}

func (r *DisconnectRequest) To() *Node {
	return r.to
}

func (r *DisconnectRequest) AssocTo(n *Node) Message {
	o := *r
	o.to = n
	return &o
}

func (r *NeighborRequest) To() *Node {
	return r.to
}

func (r *NeighborRequest) AssocTo(n *Node) Message {
	o := *r
	o.to = n
	return &o
}

func (r *NeighborRefuse) To() *Node {
	return r.to
}

func (r *NeighborRefuse) AssocTo(n *Node) Message {
	o := *r
	o.to = n
	return &o
}

func (r *ShuffleRequest) To() *Node {
	return r.to
}

func (r *ShuffleRequest) AssocTo(n *Node) Message {
	o := *r
	o.to = n
	return &o
}

func (r *ShuffleReply) To() *Node {
	return r.to
}

func (r *ShuffleReply) AssocTo(n *Node) Message {
	o := *r
	o.to = n
	return &o
}

func (r *Gossip) To() *Node {
	return r.to
}

func (r *Gossip) AssocTo(n *Node) Message {
	o := *r
	o.to = n
	return &o
}
